#!/bin/sh

ffmpeg -i "$1".mkv -vn -ac 2 -ar 44100 -ab 320k -f mp3 "$2".mp3 && ffmpeg -i "$2".mp3 -af "volume=20dB, afftdn=nf=-25" "$2"-2.mp3 && ffmpeg -i "$2"-2.mp3 -af "highpass=f=200, lowpass=f=2000" "$2"-3.mp3 && rm "$2".mp3 "$2"-2.mp3 && mv "$2"-3.mp3 "$2".mp3
