#!/bin/sh
set -eu

interval=0.25

read() {
    repos
    sleep ${interval}
    xdotool click 3
    sleep ${interval}
    # xdotool mousemove_relative -- 15 -175
    xdotool key "e"
    # sleep ${interval}
    # xdotool click 1
    sleep ${interval}
    xdotool key "ctrl+Tab"
    sleep ${interval}
    xdotool mousemove 400 130
    sleep ${interval}
    xdotool click 1
    sleep ${interval}
    xdotool key "ctrl+a" "BackSpace" "ctrl+v"
    sleep ${interval}
    xdotool type " label:sales"
    sleep ${interval}
    xdotool key "enter"
    sleep ${interval}
}

read_name_only() {
    sleep ${interval}
    xdotool key "ctrl+shift+Tab"
    sleep ${interval}
    xdotool mousemove 718 824
    sleep ${interval}
    xdotool click 1
    xdotool click 1
    xdotool click 1
    sleep ${interval}
    xdotool key "ctrl+c"
    sleep ${interval}
    xdotool key "ctrl+Tab"
    sleep ${interval}
    xdotool mousemove 400 130
    sleep ${interval}
    xdotool click 1
    sleep ${interval}
    xdotool key "ctrl+a" "BackSpace" "ctrl+v"
    sleep ${interval}
    xdotool type " label:sales"
    sleep ${interval}
    xdotool key "enter"
    sleep ${interval}
}

repos() {
    sleep ${interval}
    xdotool key "ctrl+shift+Tab"
    sleep ${interval}
    xdotool mousemove 1450 195
    sleep ${interval}
    xdotool click 1
    sleep 0.5
    # xdotool key "Page_Down"
    xdotool mousemove 718 833
    sleep ${interval}
}

label() {
    sleep ${interval}
    xdotool key "ctrl+shift+Tab"
    sleep ${interval}
    xdotool mousemove 745 195
    sleep ${interval}
    xdotool click 1
    sleep ${interval}
    xdotool mousemove_relative -- 10 55
    sleep ${interval}
    xdotool click 1
    sleep ${interval}
    xdotool type "CO-PAM"
    sleep ${interval}
    xdotool mousemove_relative -- 10 45
    sleep ${interval}
    xdotool click 1
    sleep ${interval}
    xdotool mousemove_relative -- 0 60
    sleep ${interval}
    xdotool click 1
    sleep ${interval}
    xdotool key "ctrl+Tab"
    sleep ${interval}
    read
}

case "$1" in
    "read") read ;;
    "read_name_only") read_name_only ;;
    "repos") repos ;;
    "label") label ;;
esac
